version: '2'
services:

  rails:
    build: ./app
    command: /var/www/app/entrypoint.sh
    # command: tail -f /dev/null
    environment:
      - RAILS_ROOT=/var/www/app
      - RAILS_ENV=development
      - APP_DATABASE_PASSWORD=WRJjQ3VA
      # - RAILS_LOG_TO_STDOUT=true
      # - RACK_ENV=development
      # - MALLOC_ARENA_MAX=2
      # - RAILS_MAX_THREADS=1
      # - RAILS_MAX_DB_CONNECTIONS=5
    volumes:
      - ./app:/var/www/app
      - ./app/bundle:/usr/local/bundle
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000

  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=rails
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=WRJjQ3VA
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.3-alpine
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379

