version: '2'
services:

  rails:
    build: ./app
    restart: always
    command: /var/www/app/entrypoint.sh
    environment:
      - RAILS_ROOT=/var/www/app
      - RAILS_ENV=development
      - APP_DATABASE_PASSWORD=WRJjQ3VA
      - RAILS_MAX_DB_CONNECTIONS=5
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./app:/var/www/app
      - ./app/bundle:/usr/local/bundle
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000

  sidekiq:
    build: ./app
    command: /var/www/app/entrypoint-sidekiq.sh
    environment:
      - RAILS_ROOT=/var/www/app
      - RAILS_ENV=development
      - APP_DATABASE_PASSWORD=WRJjQ3VA
      - RAILS_MAX_DB_CONNECTIONS=5
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - postgres
      - redis
      - crawler
    volumes_from:
      - rails

  postgres:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_DB=rails
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=WRJjQ3VA
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.3-alpine
    restart: always
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
  
  crawler:
    build: ./crawler
    restart: always
    command: npm run dev
    user: root
    volumes:
        - ./crawler/app:/app
    ports:
      - 3001:3000


